"""empty message

<<<<<<< HEAD:app/migrations/versions/5a08038a353d_.py
Revision ID: 5a08038a353d
Revises: 
Create Date: 2022-10-14 08:30:15.545157
=======
Revision ID: 2719917faf70
Revises: 
Create Date: 2022-10-14 06:44:27.553965
>>>>>>> 2fa142ccf3d116ee0be0dae3d1d265ccfcf6a030:app/migrations/versions/2719917faf70_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:app/migrations/versions/5a08038a353d_.py
revision = '5a08038a353d'
=======
revision = '2719917faf70'
>>>>>>> 2fa142ccf3d116ee0be0dae3d1d265ccfcf6a030:app/migrations/versions/2719917faf70_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PROGRAMS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Program_Name', sa.String(length=100), nullable=False),
    sa.Column('Program_Acronym', sa.String(length=50), nullable=False),
    sa.Column('Year', sa.Integer(), nullable=False),
    sa.Column('Class_Code', sa.String(length=50), nullable=True),
    sa.Column('Project_Code', sa.String(length=50), nullable=True),
    sa.Column('ISEO_Code', sa.String(length=50), nullable=False),
    sa.Column('UWA_Mobility_Grant_Project_Grant_Number', sa.String(length=50), nullable=True),
    sa.Column('UWA_Admin_Funding_Project_Grant_Number', sa.String(length=50), nullable=True),
    sa.Column('Program_Type', sa.String(length=50), nullable=False),
    sa.Column('CITIZENS_PR', sa.Boolean(), nullable=True),
    sa.Column('SHORT_TERM_GRANT', sa.Boolean(), nullable=True),
    sa.Column('SEMESTER_GRANT', sa.Boolean(), nullable=True),
    sa.Column('Funding_Acquittal_Date', sa.Date(), nullable=True),
    sa.Column('Project_Completion_Submission_Date', sa.Date(), nullable=True),
    sa.Column('Project_Completion_Report_Link', sa.String(), nullable=True),
    sa.Column('Refund_Utilisation_Commonwealth_Date', sa.Date(), nullable=True),
    sa.Column('Commonwealth_Refund_Invoice_Link', sa.String(), nullable=True),
    sa.Column('Statutory_Decleration_Date', sa.Date(), nullable=True),
    sa.Column('Statutory_Decleration_Link', sa.String(), nullable=True),
    sa.Column('Original_Project_Schedule', sa.String(), nullable=True),
    sa.Column('Deed_Of_Variation_One', sa.String(), nullable=True),
    sa.Column('Deed_Of_Variation_Two', sa.String(), nullable=True),
    sa.Column('Deed_Of_Variation_Three', sa.String(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('Class_Code'),
    sa.UniqueConstraint('ISEO_Code'),
    sa.UniqueConstraint('Project_Code')
    )
    op.create_table('UNIVERSITIES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('University_Acronym', sa.String(length=120), nullable=False),
    sa.Column('University_Name', sa.String(length=100), nullable=False),
    sa.Column('ABN', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=False),
    sa.Column('Password_Hash', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USER_Username'), ['Username'], unique=True)

    op.create_table('CAMPUSES',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('University_Id', sa.String(length=50), nullable=False),
    sa.Column('Campus_Name', sa.String(length=50), nullable=False),
    sa.Column('Campus_State', sa.Enum('WA', 'QLD', 'NT', 'NSW', 'SA', 'TAS', name='state'), nullable=True),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GRANTSBYUNIVERSITY',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('University_Id', sa.String(length=50), nullable=False),
    sa.Column('Allocation_Year', sa.Integer(), nullable=True),
    sa.Column('Member_Status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('PROGRAMSBYUNIVERSITY',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Allocation_Year', sa.Integer(), nullable=True),
    sa.Column('Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Grants_Allocated', sa.Integer(), nullable=True),
    sa.Column('Grant_Type', sa.Enum('Mobility', 'Language', 'Internship', name='granttype'), nullable=False),
    sa.Column('Program_Id', sa.Integer(), nullable=False),
    sa.Column('University_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Program_Id'], ['PROGRAMS.id'], ),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('STUDENTS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('University_Id', sa.String(length=50), nullable=False),
    sa.Column('Campus_Id', sa.String(length=50), nullable=False),
    sa.Column('Student_Number', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=50), nullable=True),
    sa.Column('First_Name', sa.String(length=50), nullable=False),
    sa.Column('Preferred_Name', sa.String(length=50), nullable=True),
    sa.Column('Last_Name', sa.String(length=50), nullable=False),
    sa.Column('Address_Line_One', sa.String(length=50), nullable=True),
    sa.Column('Address_Line_Two', sa.String(length=50), nullable=True),
    sa.Column('City', sa.String(length=50), nullable=True),
    sa.Column('Postcode', sa.Integer(), nullable=True),
    sa.Column('State', sa.String(length=50), nullable=True),
    sa.Column('Country', sa.String(length=50), nullable=True),
    sa.Column('Date_Of_Birth', sa.Date(), nullable=True),
    sa.Column('Phone_Number', sa.String(length=50), nullable=True),
    sa.Column('Student_Email', sa.String(length=100), nullable=True),
    sa.Column('Gender', sa.String(length=50), nullable=True),
    sa.Column('BSB', sa.String(length=50), nullable=True),
    sa.Column('Account_Number', sa.Integer(), nullable=True),
    sa.Column('Field_Of_Study', sa.String(length=50), nullable=True),
    sa.Column('Country_Of_Birth', sa.String(length=50), nullable=True),
    sa.Column('Indigenous_Australian', sa.Boolean(), nullable=True),
    sa.Column('Disability', sa.Boolean(), nullable=True),
    sa.Column('Aus_Citizen', sa.Boolean(), nullable=True),
    sa.Column('CITIZENS_PR', sa.Boolean(), nullable=True),
    sa.Column('Notes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['Campus_Id'], ['CAMPUSES.id'], ),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('GRANTS',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Start_Date', sa.Date(), nullable=True),
    sa.Column('End_Date', sa.Date(), nullable=True),
    sa.Column('Period', sa.String(length=50), nullable=False),
    sa.Column('Year_Undertaken', sa.Integer(), nullable=True),
    sa.Column('Program_Id', sa.Integer(), nullable=False),
    sa.Column('Student_Id', sa.Integer(), nullable=False),
    sa.Column('University_Id', sa.Integer(), nullable=False),
    sa.Column('Campus_Id', sa.Integer(), nullable=False),
    sa.Column('Grant_Type', sa.Enum('Mobility', 'Language', 'Internship', name='granttype'), nullable=False),
    sa.Column('Awarded', sa.Boolean(), nullable=True),
    sa.Column('UWA_Business_Unit', sa.Integer(), nullable=True),
    sa.Column('Payment_Date', sa.Date(), nullable=True),
    sa.Column('Payment_Amount', sa.Integer(), nullable=False),
    sa.Column('UWA_Account_Number', sa.Integer(), nullable=True),
    sa.Column('Funding_Round', sa.String(length=50), nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Forms_Received', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Campus_Id'], ['CAMPUSES.id'], ),
    sa.ForeignKeyConstraint(['Program_Id'], ['PROGRAMS.id'], ),
    sa.ForeignKeyConstraint(['Student_Id'], ['STUDENTS.id'], ),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GRANTS')
    op.drop_table('STUDENTS')
    op.drop_table('PROGRAMSBYUNIVERSITY')
    op.drop_table('GRANTSBYUNIVERSITY')
    op.drop_table('CAMPUSES')
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_Username'))

    op.drop_table('USER')
    op.drop_table('UNIVERSITIES')
    op.drop_table('PROGRAMS')
    # ### end Alembic commands ###
