"""empty message

Revision ID: 46163a86f10b
Revises: eb984ed6ffa2
Create Date: 2022-10-04 13:09:22.423646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46163a86f10b'
down_revision = 'eb984ed6ffa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.drop_column('Mobility_Grants_Utilised_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Mobility_Grants_Utilised_2', sa.NUMERIC(), nullable=True))

    # ### end Alembic commands ###
