"""empty message

Revision ID: 4bea30fe29bb
Revises: 46163a86f10b
Create Date: 2022-10-04 15:21:37.994465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bea30fe29bb'
down_revision = '46163a86f10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Mobility_Grants_Utilised_2', sa.Numeric(precision=15, scale=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.drop_column('Mobility_Grants_Utilised_2')

    # ### end Alembic commands ###
