"""empty message

<<<<<<<< HEAD:app/migrations/versions/41aa1e237616_.py
Revision ID: 41aa1e237616
Revises: 
Create Date: 2022-09-29 16:47:16.263656
========
Revision ID: 9fdf8041b9ad
Revises: 
Create Date: 2022-09-29 07:42:36.505694
>>>>>>>> 981f4a26a7a8cd0b0d38ae7cfb65c5513f89b352:app/migrations/versions/9fdf8041b9ad_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:app/migrations/versions/41aa1e237616_.py
revision = '41aa1e237616'
========
revision = '9fdf8041b9ad'
>>>>>>>> 981f4a26a7a8cd0b0d38ae7cfb65c5513f89b352:app/migrations/versions/9fdf8041b9ad_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PROGRAMS',
    sa.Column('Program_Id', sa.String(length=50), nullable=False),
    sa.Column('Program_Name', sa.String(length=100), nullable=True),
    sa.Column('Program_Acronym', sa.String(length=50), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Class_Code', sa.String(length=50), nullable=True),
    sa.Column('Project_Code', sa.String(length=50), nullable=True),
    sa.Column('ISEO_Code', sa.String(length=50), nullable=True),
    sa.Column('UWA_Mobility_Grant_Project_Grant_Number', sa.String(length=50), nullable=True),
    sa.Column('UWA_Admin_Funding_Project_Grant_Number', sa.String(length=50), nullable=True),
    sa.Column('Program_Type', sa.String(length=50), nullable=True),
    sa.Column('Project_Status', sa.String(length=50), nullable=True),
    sa.Column('Eligibility_Ids', sa.String(length=50), nullable=True),
    sa.Column('Funding_Acquittal_Date', sa.Date(), nullable=True),
    sa.Column('Project_Completion_Submission_Date', sa.Date(), nullable=True),
    sa.Column('Project_Completion_Report_Link', sa.String(), nullable=True),
    sa.Column('Refund_Utilisation_Commonwealth_Date', sa.Date(), nullable=True),
    sa.Column('Commonwealth_Refund_Invoice_Link', sa.String(), nullable=True),
    sa.Column('Statutory_Decleration_Date', sa.Date(), nullable=True),
    sa.Column('Statutory_Decleration_Link', sa.String(), nullable=True),
    sa.Column('Original_Project_Schedule', sa.String(), nullable=True),
    sa.Column('Deed_Of_Variation_One', sa.String(), nullable=True),
    sa.Column('Deed_Of_Variation_Two', sa.String(), nullable=True),
    sa.Column('Deed_Of_Variation_Three', sa.String(), nullable=True),
    sa.Column('Mobility_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Internship_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Internship_Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Internship_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Internship_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Internship_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Internship_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Internship_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Language_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Language_Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Language_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Language_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Language_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Language_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Language_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Administration_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Administration_Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Administration_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Administration_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Administration_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Administration_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Administration_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Total_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Total_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Total_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Total_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Total_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Total_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Program_Id')
    )
    op.create_table('UNIVERSITIES',
    sa.Column('University_Id', sa.String(length=50), nullable=False),
    sa.Column('University_Acronym', sa.String(length=20), nullable=True),
    sa.Column('University_Name', sa.String(length=100), nullable=True),
    sa.Column('ABN', sa.Integer(), nullable=True),
    sa.Column('Member_Status_2014', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2015', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2016', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2017', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2018', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2019', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2020', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2021', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2022', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2023', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2024', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2025', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2026', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2027', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2028', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2029', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2030', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('University_Id')
    )
    op.create_table('USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=False),
    sa.Column('Password_Hash', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USER_Username'), ['Username'], unique=True)

    op.create_table('CAMPUSES',
    sa.Column('Campus_Id', sa.String(length=50), nullable=False),
    sa.Column('University_Id', sa.String(length=50), nullable=True),
    sa.Column('Campus_Name', sa.String(length=50), nullable=True),
    sa.Column('Campus_State', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.University_Id'], ),
    sa.PrimaryKeyConstraint('Campus_Id')
    )
    op.create_table('STUDENTS',
    sa.Column('Student_Id', sa.String(length=50), nullable=False),
    sa.Column('University_Id', sa.String(length=50), nullable=True),
    sa.Column('Campus_Id', sa.String(length=50), nullable=True),
    sa.Column('Student_Number', sa.Integer(), nullable=True),
    sa.Column('Title', sa.String(length=50), nullable=True),
    sa.Column('First_Name', sa.String(length=50), nullable=True),
    sa.Column('Preferred_Name', sa.String(length=50), nullable=True),
    sa.Column('Last_Name', sa.String(length=50), nullable=True),
    sa.Column('Address_Line_One', sa.String(length=50), nullable=True),
    sa.Column('Address_Line_Two', sa.String(length=50), nullable=True),
    sa.Column('City', sa.String(length=50), nullable=True),
    sa.Column('Postcode', sa.Integer(), nullable=True),
    sa.Column('State', sa.String(length=50), nullable=True),
    sa.Column('Country', sa.String(length=50), nullable=True),
    sa.Column('Date_Of_Birth', sa.Date(), nullable=True),
    sa.Column('Phone_Number', sa.String(length=50), nullable=True),
    sa.Column('Student_Email', sa.String(length=100), nullable=True),
    sa.Column('Gender', sa.String(length=50), nullable=True),
    sa.Column('BSB', sa.String(length=50), nullable=True),
    sa.Column('Account_Number', sa.Integer(), nullable=True),
    sa.Column('Field_Of_Study', sa.String(length=50), nullable=True),
    sa.Column('Country_Of_Birth', sa.String(length=50), nullable=True),
    sa.Column('Indigenous_Australian', sa.Boolean(), nullable=True),
    sa.Column('Disability', sa.Boolean(), nullable=True),
    sa.Column('Aus_Citizen', sa.Boolean(), nullable=True),
    sa.Column('Notes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['Campus_Id'], ['CAMPUSES.Campus_Id'], ),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.University_Id'], ),
    sa.PrimaryKeyConstraint('Student_Id')
    )
    op.create_table('PAYMENTS',
    sa.Column('Payment_Id', sa.String(length=50), nullable=False),
    sa.Column('Student_Id', sa.String(length=50), nullable=True),
    sa.Column('Program_Id', sa.String(length=50), nullable=True),
    sa.Column('UWA_Business_Unit', sa.Integer(), nullable=True),
    sa.Column('Payment_Date', sa.Date(), nullable=True),
    sa.Column('Payment_Amount', sa.Integer(), nullable=True),
    sa.Column('UWA_Account_Number', sa.Integer(), nullable=True),
    sa.Column('Funding_Round', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Program_Id'], ['PROGRAMS.Program_Id'], ),
    sa.ForeignKeyConstraint(['Student_Id'], ['STUDENTS.Student_Id'], ),
    sa.PrimaryKeyConstraint('Payment_Id')
    )
    op.create_table('GRANTS',
    sa.Column('Grant_Id', sa.String(length=50), nullable=False),
    sa.Column('Start_Date', sa.Date(), nullable=True),
    sa.Column('End_Date', sa.Date(), nullable=True),
    sa.Column('Period', sa.String(length=50), nullable=True),
    sa.Column('Program_Id', sa.String(length=50), nullable=True),
    sa.Column('Student_Id', sa.String(length=50), nullable=True),
    sa.Column('Payment_Id', sa.String(length=50), nullable=True),
    sa.Column('University_Id', sa.String(length=50), nullable=True),
    sa.Column('Campus_Id', sa.String(length=50), nullable=True),
    sa.Column('Awarded', sa.Boolean(), nullable=True),
    sa.Column('Forms_Received', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Campus_Id'], ['CAMPUSES.Campus_Id'], ),
    sa.ForeignKeyConstraint(['Payment_Id'], ['PAYMENTS.Payment_Id'], ),
    sa.ForeignKeyConstraint(['Program_Id'], ['PROGRAMS.Program_Id'], ),
    sa.ForeignKeyConstraint(['Student_Id'], ['STUDENTS.Student_Id'], ),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.University_Id'], ),
    sa.PrimaryKeyConstraint('Grant_Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GRANTS')
    op.drop_table('PAYMENTS')
    op.drop_table('STUDENTS')
    op.drop_table('CAMPUSES')
    with op.batch_alter_table('USER', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USER_Username'))

    op.drop_table('USER')
    op.drop_table('UNIVERSITIES')
    op.drop_table('PROGRAMS')
    # ### end Alembic commands ###
