"""empty message

Revision ID: bd128c1ed810
Revises: 
Create Date: 2022-09-13 20:54:21.932560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd128c1ed810'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PROGRAMS',
    sa.Column('Program_Id', sa.String(length=50), nullable=False),
    sa.Column('Program_Name', sa.String(length=100), nullable=True),
    sa.Column('Program_Acronym', sa.String(length=50), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Class_Code', sa.String(length=50), nullable=True),
    sa.Column('Project_Code', sa.String(length=50), nullable=True),
    sa.Column('ISEO_Code', sa.String(length=50), nullable=True),
    sa.Column('UWA_Mobility_Grant_Project_Grant_Number', sa.String(length=50), nullable=True),
    sa.Column('UWA_Admin_Funding_Project_Grant_Number', sa.String(length=50), nullable=True),
    sa.Column('Program_Type', sa.String(length=50), nullable=True),
    sa.Column('Project_Status', sa.String(length=50), nullable=True),
    sa.Column('Funding_Acquittal_Date', sa.Date(), nullable=True),
    sa.Column('Project_Completion_Submission_Date', sa.Date(), nullable=True),
    sa.Column('Project_Completion_Report_Link', sa.String(), nullable=True),
    sa.Column('Refund_Utilisation_Commonwealth_Date', sa.Date(), nullable=True),
    sa.Column('Commonwealth_Refund_Invoice_Link', sa.String(), nullable=True),
    sa.Column('Statutory_Decleration_Date', sa.Date(), nullable=True),
    sa.Column('Statutory_Decleration_Link', sa.String(), nullable=True),
    sa.Column('Original_Project_Schedule', sa.String(), nullable=True),
    sa.Column('Deed_Of_Variation_One', sa.String(), nullable=True),
    sa.Column('Deed_Of_Variation_Two', sa.String(), nullable=True),
    sa.Column('Deed_Of_Variation_Three', sa.String(), nullable=True),
    sa.Column('Mobility_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Mobility_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Internship_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Internship_Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Internship_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Internship_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Internship_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Internship_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Internship_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Language_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Language_Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Language_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Language_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Language_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Language_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Language_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Administration_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Administration_Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Administration_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Administration_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Administration_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Administration_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Administration_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Total_Grant_Funding_Received', sa.Integer(), nullable=True),
    sa.Column('Total_Grant_Dollar_Size', sa.Integer(), nullable=True),
    sa.Column('Total_Grant_Funding_Utilised', sa.Integer(), nullable=True),
    sa.Column('Total_Grant_Funding_Remaining', sa.Integer(), nullable=True),
    sa.Column('Total_Grants_Received', sa.Integer(), nullable=True),
    sa.Column('Total_Grants_Utilised', sa.Integer(), nullable=True),
    sa.Column('Total_Grants_Remaining', sa.Integer(), nullable=True),
    sa.Column('Notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Program_Id')
    )
    op.create_table('UNIVERSITIES',
    sa.Column('University_Id', sa.String(length=50), nullable=False),
    sa.Column('University_Name', sa.String(length=100), nullable=True),
    sa.Column('ABN', sa.Integer(), nullable=True),
    sa.Column('Member_Status_2014', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2015', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2016', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2017', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2018', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2019', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2020', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2021', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2022', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('University_Id')
    )
    op.create_table('USER',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=20), nullable=False),
    sa.Column('Password_Hash', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USER_Username'), 'USER', ['Username'], unique=True)
    op.create_table('CAMPUSES',
    sa.Column('Campus_Id', sa.String(length=50), nullable=False),
    sa.Column('University_Id', sa.String(length=50), nullable=True),
    sa.Column('Campus_Name', sa.String(length=50), nullable=True),
    sa.Column('Campus_State', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.University_Id'], ),
    sa.PrimaryKeyConstraint('Campus_Id')
    )
    op.create_table('STUDENTS',
    sa.Column('Student_Id', sa.String(length=50), nullable=False),
    sa.Column('University_Id', sa.String(length=50), nullable=True),
    sa.Column('Campus_Id', sa.String(length=50), nullable=True),
    sa.Column('Student_Number', sa.Integer(), nullable=True),
    sa.Column('Title', sa.String(length=50), nullable=True),
    sa.Column('First_Name', sa.String(length=50), nullable=True),
    sa.Column('Preferred_Name', sa.String(length=50), nullable=True),
    sa.Column('Last_Name', sa.String(length=50), nullable=True),
    sa.Column('Address_Line_One', sa.String(length=50), nullable=True),
    sa.Column('Address_Line_Two', sa.String(length=50), nullable=True),
    sa.Column('City', sa.String(length=50), nullable=True),
    sa.Column('Postcode', sa.Integer(), nullable=True),
    sa.Column('State', sa.String(length=50), nullable=True),
    sa.Column('Country', sa.String(length=50), nullable=True),
    sa.Column('Date_Of_Birth', sa.Date(), nullable=True),
    sa.Column('Phone_Number', sa.String(length=50), nullable=True),
    sa.Column('Student_Email', sa.String(length=100), nullable=True),
    sa.Column('Gender', sa.String(length=50), nullable=True),
    sa.Column('BSB', sa.String(length=50), nullable=True),
    sa.Column('Account_Number', sa.Integer(), nullable=True),
    sa.Column('Field_Of_Study', sa.String(length=50), nullable=True),
    sa.Column('Country_Of_Birth', sa.String(length=50), nullable=True),
    sa.Column('Indigenous_Australian', sa.Boolean(), nullable=True),
    sa.Column('Disability', sa.Boolean(), nullable=True),
    sa.Column('Aus_Citizen', sa.Boolean(), nullable=True),
    sa.Column('Notes', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['Campus_Id'], ['CAMPUSES.Campus_Id'], ),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.University_Id'], ),
    sa.PrimaryKeyConstraint('Student_Id')
    )
    op.create_table('PAYMENTS',
    sa.Column('Payment_Id', sa.String(length=50), nullable=False),
    sa.Column('Student_Id', sa.String(length=50), nullable=True),
    sa.Column('Program_Id', sa.String(length=50), nullable=True),
    sa.Column('UWA_Business_Unit', sa.Integer(), nullable=True),
    sa.Column('Payment_Date', sa.Date(), nullable=True),
    sa.Column('Payment_Amount', sa.Integer(), nullable=True),
    sa.Column('UWA_Account_Number', sa.Integer(), nullable=True),
    sa.Column('Funding_Round', sa.String(length=50), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['Program_Id'], ['PROGRAMS.Program_Id'], ),
    sa.ForeignKeyConstraint(['Student_Id'], ['STUDENTS.Student_Id'], ),
    sa.PrimaryKeyConstraint('Payment_Id')
    )
    op.create_table('GRANTS',
    sa.Column('Grant_Id', sa.String(length=50), nullable=False),
    sa.Column('Program_Id', sa.String(length=50), nullable=True),
    sa.Column('Student_Id', sa.String(length=50), nullable=True),
    sa.Column('Payment_Id', sa.String(length=50), nullable=True),
    sa.Column('University_Id', sa.String(length=50), nullable=True),
    sa.Column('Campus_Id', sa.String(length=50), nullable=True),
    sa.Column('Awarded', sa.Boolean(), nullable=True),
    sa.Column('Forms_Received', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Campus_Id'], ['CAMPUSES.Campus_Id'], ),
    sa.ForeignKeyConstraint(['Payment_Id'], ['PAYMENTS.Payment_Id'], ),
    sa.ForeignKeyConstraint(['Program_Id'], ['PROGRAMS.Program_Id'], ),
    sa.ForeignKeyConstraint(['Student_Id'], ['STUDENTS.Student_Id'], ),
    sa.ForeignKeyConstraint(['University_Id'], ['UNIVERSITIES.University_Id'], ),
    sa.PrimaryKeyConstraint('Grant_Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('GRANTS')
    op.drop_table('PAYMENTS')
    op.drop_table('STUDENTS')
    op.drop_table('CAMPUSES')
    op.drop_index(op.f('ix_USER_Username'), table_name='USER')
    op.drop_table('USER')
    op.drop_table('UNIVERSITIES')
    op.drop_table('PROGRAMS')
    # ### end Alembic commands ###
