"""empty message

Revision ID: bf7c76a64552
Revises: 4bea30fe29bb
Create Date: 2022-10-04 15:46:48.323836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7c76a64552'
down_revision = '4bea30fe29bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.drop_column('Mobility_Grants_Utilised_2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Mobility_Grants_Utilised_2', sa.NUMERIC(precision=15, scale=5), nullable=True))

    # ### end Alembic commands ###
