"""empty message

Revision ID: c115e29724cb
Revises: 
Create Date: 2022-09-05 20:40:17.395578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c115e29724cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('university',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('University_Name', sa.String(), nullable=True),
    sa.Column('ABN', sa.Integer(), nullable=True),
    sa.Column('Member_Status_2014', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2015', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2016', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2017', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2018', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2019', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2020', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2021', sa.Boolean(), nullable=True),
    sa.Column('Member_Status_2022', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=180), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('University_ID', sa.Integer(), nullable=True),
    sa.Column('Campus_Name', sa.String(length=50), nullable=True),
    sa.Column('Campus_State', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['University_ID'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_Number', sa.Integer(), nullable=True),
    sa.Column('University_ID', sa.Integer(), nullable=True),
    sa.Column('Campus_ID', sa.Integer(), nullable=True),
    sa.Column('First_Name', sa.String(length=50), nullable=True),
    sa.Column('Last_Name', sa.String(length=50), nullable=True),
    sa.Column('Prefered_Name', sa.String(length=50), nullable=True),
    sa.Column('Title', sa.String(length=50), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Adress_Line_One', sa.String(length=50), nullable=True),
    sa.Column('Adress_Line_Two', sa.String(length=50), nullable=True),
    sa.Column('City', sa.String(length=50), nullable=True),
    sa.Column('State', sa.String(length=50), nullable=True),
    sa.Column('Nationality', sa.String(length=50), nullable=True),
    sa.Column('Phone_Number', sa.Integer(), nullable=True),
    sa.Column('BSB', sa.Integer(), nullable=True),
    sa.Column('Account_Number', sa.Integer(), nullable=True),
    sa.Column('Country_Of_Birth', sa.String(length=50), nullable=True),
    sa.Column('Indigenous_or_Torres_Strait_Australian', sa.Boolean(), nullable=True),
    sa.Column('Disability', sa.Boolean(), nullable=True),
    sa.Column('AUS_Citizen', sa.Boolean(), nullable=True),
    sa.Column('Notes', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['Campus_ID'], ['campus.id'], ),
    sa.ForeignKeyConstraint(['University_ID'], ['university.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('campus')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('university')
    op.drop_table('Grants')
    # ### end Alembic commands ###
