"""empty message

Revision ID: eb984ed6ffa2
Revises: e008c0df8a99
Create Date: 2022-10-04 13:04:50.029538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb984ed6ffa2'
down_revision = 'e008c0df8a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Mobility_Grants_Utilised_2', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.drop_column('Mobility_Grants_Utilised_2')

    # ### end Alembic commands ###
