"""empty message

Revision ID: fc8c591bc498
Revises: 7a1634e61330
Create Date: 2022-09-15 21:03:43.185303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc8c591bc498'
down_revision = '7a1634e61330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.drop_column('Total_Grant_Dollar_Size')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('PROGRAMS', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Total_Grant_Dollar_Size', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
